stages:
  - docker-build
  - deploy

include:
  - project: "tournamentfox/ci-templates"
    file: "default/docker-build.yml"
    ref: main
  - project: "tournamentfox/ci-templates"
    file: "default/deploy.yml"
    ref: main
